version: '3'
services:
  flask:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - OPENSEARCH_HOST=opensearch:9200
    depends_on:
      - opensearch
    networks:
      - app-network

  opensearch:
    image: opensearchproject/opensearch:2.18.0
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=123@QWE#asd
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./install_ik.sh:/usr/share/opensearch/install-ik.sh # 安装分词器脚本
    networks:
      - app-network
    command: ["/bin/bash", "-c", "chmod +x /usr/share/opensearch/install-ik.sh && /usr/share/opensearch/install-ik.sh"] # 执行脚本

volumes:
  opensearch-data:

networks:
  app-network:
    driver: bridge